# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc


# put strawberry perl first in path
PATH=/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Python27:/c/Python27/Scripts:/c/Program\ Files/MySQL/MySQL\ Utilities\ 1.6:/c/Program\ Files/MySQL/MySQL\ Server\ 5.7/bin:/c/Program\ Files/MiKTeX\ 2.9/miktex/bin/x64:/c/Program\ Files/Docker\ Toolbox:/c/Program\ Files\ \(x86\)/Pandoc:$PATH
