alias cdw="cd /g/ALUMNI/Jake\ T/datawarehouse/"
alias cdd="cd ~/Desktop"
alias callprep="cd /g/ALUMNI/Jake\ T/datawarehouse && perl callPrepScripts.pl"
alias mysql="winpty mysql"
# alias mysqlw="winpty mysql -u adc -h 10.40.9.145 --password='goBigBlue'"
alias mysqlw="mysql -h 10.40.9.145 -u root commits"
